# Generated by Django 5.2.7 on 2025-12-10 13:49

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_ai_recommend_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sake',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
