# Generated by Django 4.2.27 on 2025-12-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sake_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sake',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userstamp',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userstamp',
            name='brewery',
        ),
        migrations.RemoveField(
            model_name='userstamp',
            name='rally',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='StampRally',
        ),
        migrations.DeleteModel(
            name='UserStamp',
        ),
    ]
