# Generated by Django 4.2.27 on 2026-01-03 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_review_event_remove_review_sake_and_more'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'イベント', 'verbose_name_plural': 'イベント一覧'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_at',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='イベントの住所'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='alcohol_types',
            field=models.JSONField(default=list, verbose_name='アルコールのタイプ'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時刻'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='料金'),
        ),
        migrations.AddField(
            model_name='event',
            name='keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='ハッシュタグキーワード'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時刻'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='イベントのリンク'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer_supa_id',
            field=models.CharField(blank=True, db_index=True, help_text='Supabase User ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sakes_featured',
            field=models.ManyToManyField(blank=True, to='api.sake', verbose_name='提供されるお酒'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='イベントのタイトル'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='開催場所'),
        ),
    ]
