# Generated by Django 4.2.27 on 2026-01-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_options_remove_event_start_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reserved_user_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='予約済みユーザーID'),
        ),
    ]
