# Generated by Django 4.2.27 on 2026-01-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_description_event_decription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='decription',
            new_name='description',
        ),
    ]
