# Generated by Django 4.2.27 on 2026-01-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_decription_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='alcohol_types',
            new_name='alcoholTypes',
        ),
    ]
