# Generated by Django 4.2.27 on 2026-01-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_alcohol_types_event_alcoholtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
