# Generated by Django 4.2.27 on 2026-01-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_review_event_remove_review_sake_and_more'),
        ('event', '0007_remove_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reserved_user_ids',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='予約済みユーザーID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sakes_featured',
            field=models.ManyToManyField(blank=True, null=True, to='api.sake', verbose_name='提供されるお酒'),
        ),
    ]
