# Generated by Django 5.2.4 on 2025-11-26 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommend', '0003_make_user_supa_id_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='SakeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('brewery_name', models.CharField(blank=True, help_text='酒蔵名（任意）', max_length=200)),
                ('sweetness_level', models.IntegerField(blank=True, help_text='甘さの度合い（1:辛口 〜 5:甘口）', null=True)),
                ('aroma_level', models.IntegerField(blank=True, help_text='香りの強さ（1:控えめ 〜 5:芳醇）', null=True)),
                ('alcohol_content', models.FloatField(blank=True, help_text='アルコール度数', null=True)),
                ('price_range', models.CharField(blank=True, help_text='価格帯（例: 1000-2000円）', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='recommendeditem',
            name='score',
            field=models.FloatField(default=0.0, help_text='レコメンドスコア（GPTからの評価スコア）'),
        ),
        migrations.AlterField(
            model_name='recommendeditem',
            name='title',
            field=models.CharField(help_text='酒の名前（SakeProfileと別に保持）', max_length=200),
        ),
        migrations.AlterField(
            model_name='recommendeditem',
            name='sake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ai_recommend.sakeprofile'),
        ),
    ]
