# Generated by Django 5.2.4 on 2025-12-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommend', '0004_sakeprofile_alter_recommendeditem_score_and_more'),
        ('api', '0002_add_ai_recommend_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendeditem',
            name='sake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.sake'),
        ),
        migrations.AlterField(
            model_name='recommendeditem',
            name='title',
            field=models.CharField(help_text='酒の名前（sakeから取得可能だが、GPT生成時にも保持）', max_length=200),
        ),
        migrations.DeleteModel(
            name='SakeProfile',
        ),
    ]
