# Generated by Django 5.2.7 on 2025-12-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommend', '0005_alter_recommendeditem_sake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendeditem',
            name='user_supa_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
