# Generated by Django 5.2.7 on 2025-12-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommend', '0006_alter_recommendeditem_user_supa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='user_supa_id',
            field=models.CharField(db_index=True, help_text='SupabaseのUser ID'),
        ),
    ]
