export const EVENTS = [
  {
    id: '1',
    title: '伏見酒蔵めぐり 2024秋',
    date: '2024-10-15',
    location: '京都市伏見区',
    prefecture: '京都府',
    image: 'https://picsum.photos/800/600?random=1',
    price: 3500,
    hashtags: ['#一人参加OK', '#初心者向け', '#飲み比べ', '#伝統文化'],
    description: '歴史ある伏見の酒蔵を巡りながら、秋の限定酒を楽しむツアーです。初心者の方でも楽しめるガイド付き。',
    availableSeats: 5,
  },
  {
    id: '2',
    title: '灘五郷・日本酒フェス',
    date: '2024-11-03',
    location: '神戸市東灘区',
    prefecture: '兵庫県',
    image: 'https://picsum.photos/800/600?random=2',
    price: 4000,
    hashtags: ['#飲み放題', '#グルメ', '#ワイワイ楽しむ'],
    description: '灘の銘酒が集結！地元の名産品とのペアリングを楽しめる大規模イベント。',
    availableSeats: 20,
  },
  {
    id: '3',
    title: '雪国酒蔵見学ツアー in 新潟',
    date: '2024-12-10',
    location: '新潟県南魚沼市',
    prefecture: '新潟県',
    image: 'https://picsum.photos/800/600?random=3',
    price: 5000,
    hashtags: ['#一人参加OK', '#ディープな体験', '#杜氏に会える'],
    description: '雪の中で醸される日本酒の神秘に触れる旅。普段は見られない醸造工程を見学できます。',
    availableSeats: 2,
  },
  {
    id: '4',
    title: '春の酒蔵ジャズナイト',
    date: '2025-03-20',
    location: '金沢市',
    prefecture: '石川県',
    image: 'https://picsum.photos/800/600?random=4',
    price: 6500,
    hashtags: ['#音楽とお酒', '#デートにおすすめ', '#ナイトイベント'],
    description: '酒蔵の幻想的な雰囲気の中でジャズライブを開催。特別な夜をお過ごしください。',
    availableSeats: 12,
  },
];

export const CHAT_GROUPS = [
  {
    id: 'g1',
    eventId: '1',
    eventName: '伏見酒蔵めぐり 2024秋',
    eventImage: 'https://picsum.photos/100/100?random=1',
    lastMessage: '当日はよろしくお願いします！',
    unreadCount: 2,
  },
  {
    id: 'g2',
    eventId: '3',
    eventName: '雪国酒蔵見学ツアー',
    eventImage: 'https://picsum.photos/100/100?random=3',
    lastMessage: '持ち物について質問です。',
    unreadCount: 0,
  }
];

export const MOCK_MESSAGES = [
  {
    id: 'm1',
    userId: 'u2',
    userName: '日本酒太郎',
    avatar: 'https://picsum.photos/50/50?random=10',
    content: '初めまして！参加予定の日本酒太郎です。よろしくお願いします。',
    timestamp: '10:00',
    isMe: false,
  },
  {
    id: 'm2',
    userId: 'u3',
    userName: 'Sake Lover',
    avatar: 'https://picsum.photos/50/50?random=11',
    content: '私も一人参加です！楽しみですね🍶',
    timestamp: '10:05',
    isMe: false,
  },
  {
    id: 'm3',
    userId: 'me',
    userName: '自分',
    avatar: 'https://picsum.photos/50/50?random=12',
    content: 'よろしくお願いします！当日はどの辺りで集合しましょうか？',
    timestamp: '10:15',
    isMe: true,
  },
];

export const STAMP_SPOTS = [
  {
    id: 's1',
    name: '月桂冠大倉記念館',
    prefecture: '京都府',
    description: '伏見の酒造りの歴史を学べる博物館。きき酒も楽しめます。',
    image: 'https://picsum.photos/400/300?random=20',
    collected: true,
    collectedAt: '2024-05-01',
    lat: 34.9298,
    lng: 135.7607,
  },
  {
    id: 's2',
    name: '黄桜カッパカントリー',
    prefecture: '京都府',
    description: '黄桜の直営店。限定のお酒や地ビールが味わえます。',
    image: 'https://picsum.photos/400/300?random=21',
    collected: false,
    lat: 34.9315,
    lng: 135.7620,
  },
  {
    id: 's3',
    name: '白鶴酒造資料館',
    prefecture: '兵庫県',
    description: '伝統的な酒造りの工程を等身大の人形で再現。',
    image: 'https://picsum.photos/400/300?random=22',
    collected: false,
    lat: 34.7104,
    lng: 135.2638,
  },
  {
    id: 's4',
    name: '今代司酒造',
    prefecture: '新潟県',
    description: '新潟駅から歩いて行ける酒蔵。全量純米仕込みにこだわり。',
    image: 'https://picsum.photos/400/300?random=23',
    collected: false,
    lat: 37.9189,
    lng: 139.0664,
  },
];
