# Generated by Django 4.2.27 on 2025-12-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamprally', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stamp',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stamp',
            name='user_supa_id',
            field=models.CharField(blank=True, db_index=True, help_text='Supabase User ID', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stamp',
            unique_together={('user_supa_id', 'checkpoint')},
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='user',
        ),
    ]
