# Generated by Django 4.2.27 on 2026-01-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_users'),
        ('stamprally', '0003_stamp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
