# Generated by Django 4.2.27 on 2026-01-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_users'),
        ('stamprally', '0004_alter_stamp_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stamp',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AlterUniqueTogether(
            name='stamp',
            unique_together={('user', 'checkpoint')},
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='user_supa_id',
        ),
    ]
