# Generated by Django 4.2.27 on 2025-12-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_password_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
